name: Create a release

on:
  workflow_dispatch:
    inputs:
      semver:
        description: The semver to use
        required: true
        default: patch
        type: choice
        options:
          - patch
          - minor
          - major
      commit-message:
        description: 'The commit message template'
        required: false
        default: 'release: {version}'
  pull_request:
    types: [closed]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Node.js runtime on build
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - uses: nearform/optic-release-automation-action@v2
        with:
          github-token: ${{ secrets.github_token }}
          semver: ${{ github.event.inputs.semver }}
          commit-message: ${{ github.event.inputs.commit-message }}
          sync-semver-tags: true
          build-command: |
            echo 'installing husky hooks..'
            npm ci
